//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPA_MoviePosterAwards.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_User
    {
        public System.Guid Id { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string Avatar { get; set; }
        public string Cover { get; set; }
        public Nullable<bool> Limit { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<System.DateTime> Change_Time { get; set; }
    }
}
