//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPA_MoviePosterAwards.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoviePosterAwardsEntities : DbContext
    {
        public MoviePosterAwardsEntities()
            : base("name=MoviePosterAwardsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basic_Celebrity> Basic_Celebrity { get; set; }
        public virtual DbSet<Basic_Movie> Basic_Movie { get; set; }
        public virtual DbSet<Basic_Poster> Basic_Poster { get; set; }
        public virtual DbSet<Basic_User> Basic_User { get; set; }
        public virtual DbSet<Step_Celeb_Movie> Step_Celeb_Movie { get; set; }
    }
}
